version: '3.1'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/TaskTrace
      - DATABASE_USER=root
      - DATABASE_PASSWORD=19229094

  db:
    image: mysql:8.1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=19229094
      - MYSQL_DATABASE=TaskTrace
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./db-dump/database-init-v1.sql:/docker-entrypoint-initdb.d/database-init-v1.sql

volumes:
  db-data:
